const levelsStyleText = `
#countrys>*[level="5"]{fill:#FF7E7E;}
#countrys>*[level="4"]{fill:#FFB57E;}
#countrys>*[level="3"]{fill:#FFE57E;}
#countrys>*[level="2"]{fill:#A8FFBE;}
#countrys>*[level="1"]{fill:#88AEFF;}
#countrys>*[level="w"]{fill:#edd1ff;}
`;

const replaceSVG = text=>{
    text = text.replace(/ transform="matrix\(1 0 0 1 (\d+)(?:\.\d+)? (\d+)(?:\.\d+)?\)" class="(.+)"/g,' x="$1" y="$2" class="$3"')
    text = text.replace(/<!--.+?-->/g,'')
    text = text.replace(/\n+/g,'\n')
    text = text.replace(/ xml:space="preserve"/g,'')
    text = text.replace(/ style="enable-background:new 0 0 \d+ \d+;?"/g,'')
    text = text.replace(/width="\d+px" height="\d+px"/g,'')
    text = text.replace(/ x="0px" y="0px"/g,'')
    text = text.replace(/ id="图层_1"/g,'')
    text = text.replace(/ version="1.1"/g,'')
    text = text.replace(/ xmlns:xlink="http:\/\/www\.w3\.org\/1999\/xlink"/g,'')
    text = text.replace(/<rect y="0" class=".+?" width="2000" height="1210"\/?>/g,'')
    text = text.replace(/'Tensentype-JiaLiDaYuanJF'/g,'字体')

    text = text.replace(/<polygon id="(.+?)" class="(.+?)" points="([^"]+)\s{0,}"\/>/g,(all,id,c,p)=>{
        return `<path id="${id}" class="${c}" d="M${p.trim().replace(/[\n\r]/g,' ').replace(/\s+/g,' ')}z" />`
    });
    // <rect id="法国" x="1" y="10" class="st1" width="100" height="1000"/>
    // <path id="法国" class="st1" d="M1 10h100v1000H1Z" />
    text = text.replace(/<rect id="(.+?)" x="(\d+)" y="(\d+)" class="(.+?)" width="(\d+)" height="(\d+)"\/>/g,(all,id,x,y,c,w,h)=>{
        // console.log(x,y,w,h)
        return `<path id="${id}" class="${c}" d="M${x} ${y}h${w}v${h}H${x}Z" />`
    });
    
    text = text.replace(/<style type="text\/css">/,'<style></style><style>'+levelsStyleText)
    return text;
};
const ver = Math.floor(+new Date()/10000).toString(36);
const replaceVersion = text => text.replace(/\{version\}/g,ver);


const { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync, rmSync } = require('fs');



const Less = require('less');

const 省代码们 = {
    北京: '11',
    天津: '12',
    河北: '13',
    山西: '14',
    内蒙古: '15',
    辽宁: '21',
    吉林: '22',
    黑龙江: '23',
    上海: '31',
    江苏: '32',
    浙江: '33',
    安徽: '34',
    福建: '35',
    江西: '36',
    山东: '37',
    河南: '41',
    湖北: '42',
    湖南: '43',
    广东: '44',
    广西: '45',
    海南: '46',
    重庆: '50',
    四川: '51',
    贵州: '52',
    云南: '53',
    西藏: '54',
    陕西: '61',
    甘肃: '62',
    青海: '63',
    宁夏: '64',
    新疆: '65',
    台湾: '71',
    香港: '81',
    澳门: '82'
};

const 直辖地区代码们 = new Set(['11','12','31','50','81','82']);
const 台湾地区们 = [
    '台北市','新北市','桃园市','台中市','台南市','高雄市',
    '基隆市','新竹市','嘉义市','新竹县','苗栗县','彰化县',
    '南投县','云林县','嘉义县','屏东县','宜兰县','花莲县',
    '台东县','澎湖县','金门县','连江县'
];

const 生成城市数据 = 输出目录=>{
    const 行政区划 = require('@province-city-china/data');
    const 城市数据 = {};

    Object.entries(省代码们).forEach(([省份,省代码])=>{
        if(省代码 === '71'){
            城市数据[省份] = 台湾地区们;
            return;
        }

        城市数据[省份] = 行政区划
            .filter(地区=>{
                if(String(地区.province) !== 省代码 || Number(地区.town) !== 0) return false;
                if(直辖地区代码们.has(省代码)) return Number(地区.area) !== 0;

                const 是地级地区 = Number(地区.city) !== 0 && Number(地区.area) === 0;
                const 是直管地区 = Number(地区.city) === 90 && Number(地区.area) !== 0;
                return (是地级地区 && !地区.name.includes('直辖县级行政区划')) || 是直管地区;
            })
            .sort((甲,乙)=>甲.code.localeCompare(乙.code))
            .map(地区=>地区.name);
    });

    writeFileSync(
        `${输出目录}/城市数据.js`,
        `globalThis.城市数据=${JSON.stringify(城市数据)};`,
        'utf8'
    );
};


const reader = async _=>{

    let xml = readFileSync('china-ex.svg','utf8');

    xml = replaceSVG(xml);
    writeFileSync('china-ex-fixed.svg',xml);


    const 输出目录 = 'public/legacy';
    if(existsSync(输出目录)) rmSync(输出目录,{ recursive: true, force: true });
    mkdirSync(输出目录,{ recursive: true });

    let html = readFileSync('html/index.html','utf8');

    html = html.replace(/<!--svg-->/,xml.replace(/^<\?xml version="1.0" encoding="utf-8"\?>\n/,''));
    html = html.replace(/\n\s+viewBox=/,' viewBox=');
    html = html.replace(/\n\s{0,}\n/g,'\n');
    html = html.replace(/\s+"/g,'"');
    html = html.replace(/\s+\/>/g,'/>');
    html = html.replace(/(\d+)\s+([\dvV]+)/g,'$1 $2');

    html = html.replace(/<style[\s\S]+<\/style>/ig,all=>all.replace(/\n\s{0,}/g,''));
    html = replaceVersion(html);
    const { minify } = require('html-minifier');

    const options = {
        includeAutoGeneratedTags: true,
        removeAttributeQuotes: true,
        removeComments: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        sortClassName: true,
        useShortDoctype: true,
        collapseWhitespace: true
    };

    html = minify(html,options);


    writeFileSync(`${输出目录}/index.html`,html,'utf8');
    const cssText = await Less.render(
        readFileSync('html/样式.less','utf8'),
        {
            optimization: 1,
            compress: true,
            yuicompress: false,
        }
    );
    writeFileSync(`${输出目录}/样式.css`,cssText.css,'utf8');
    copyFileSync('html/字体.woff',`${输出目录}/字体.woff`);
    copyFileSync('html/城市.js',`${输出目录}/城市.js`);
    生成城市数据(输出目录);
};

reader();
